export { default as AccessoriesPage	} from './AccessoriesPage';
export { default as CartPage			} from './CartPage';
export { default as ComponentsPage	} from './ComponentsPage';
export { default as HomePage			} from './HomePage';
export { default as PayoutPage		} from './PayoutPage';
export { default as PeripheralsPage	} from './PeripheralsPage';
export { default as ProductPage		} from './ProductPage';
export { default as SearchPage		} from './SearchPage';
export { default as ShoppingPage		} from './ShoppingPage';